name: Main Push

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-diff:
    uses: ./.github/workflows/check-diff.yaml
    
  deploy-backend:
    needs: check-diff
    uses: ./.github/workflows/backend-deploy.yaml
    if: needs.check-diff.outputs.backend == 'true'
    secrets: inherit
